version: '3'
services: 
  datastore:
    image: busybox
    volumes:
      - /share
      - ./docker/mysql/volumes:/var/lib/mysql
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes_from:
      - datastore
    depends_on:
      - datastore
  web:
    build:
      context: .
      dockerfile: ./docker/rails/development/Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes_from:
      - datastore
    depends_on:
      - datastore
      - db
