default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV.fetch("MYSQL_ROOT_PASSWORD", "password") %>

development:
  <<: *default
  database: rails_on_fargate_development
  host: <%= ENV.fetch("MYSQL_HOST", "db") %>

test:
  <<: *default
  database: rails_on_fargate_test
  host: <%= ENV.fetch("MYSQL_HOST", "db") %>

production:
  <<: *default
  host: <%= ENV.fetch("DB_HOST", "db") %>
  socket: <%= ENV['DB_SOCKET'] %>
  database: rails_on_fargate_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
